<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="TermsCondi.aspx.cs" Inherits="Chimbank.TermsCondiaspx" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
     <link href ="/Diseños/TerYCond.css" rel="stylesheet" type="text/css" />

</head>

<body>

    <h1 class="text-center" style="box-sizing: border-box; font-size: 33px; margin: 11px 0px 10px; font-family: OpenSans-Light; font-weight: 500; line-height: 1.1; color: rgb(15, 38, 92); text-align: center; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Aceptación de términos y condiciones</h1>
    <br class="lg" style="box-sizing: border-box; display: block; overflow: hidden; content: &quot;&quot;; margin-top: 30px; margin-bottom: 30px; color: rgb(89, 89, 89); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 100; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;" />
    <h3 style="box-sizing: border-box; font-family: &quot;Open Sans&quot;, sans-serif; font-weight: 500; line-height: 1.1; color: rgb(15, 38, 92); margin-top: 20px; margin-bottom: 10px; font-size: 28px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Declaración de Titularidad y Veracidad de la Información.</h3>
    <p style="box-sizing: border-box; margin: 0px 0px 10px; line-height: 1.8em; padding-top: 11px; color: rgb(89, 89, 89); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 100; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        Como la información aquí suministrada por mí es confidencial y básica para la vinculación como Cliente del BANCO PICHINCHA, la gestión y aprobación de cualquier producto u operación y/o la atención de mis solicitudes, peticiones, quejas o reclamos; el BANCO PICHINCHA exige que todos los datos suministrados sean exactos y se puedan verificar. Declaro que la información suministrada en este Sitio Web es de mi titularidad, concuerda con la realidad y asumo plena responsabilidad por la veracidad de la misma; cualquier inexactitud podrá acarrear su rechazo o la no aprobación de la vinculación al Banco y/o de la solicitud del (de los) producto(s), sin responsabilidad alguna por parte de BANCO PICHINCHA frente a terceros o al (a los) solicitantes. Reconozco y acepto que en el evento que la información por mí suministrada en este Sitio Web no sea de mi propiedad, induzca a una falsedad personal o sea violatoria del bien jurídico tutelado denominado “de la protección de la información y de los 
        datos” podré incurrir en tipos penales sanciónales por la Ley Penal Colombiana.</p>
    <h4 style="box-sizing: border-box; font-family: &quot;Open Sans&quot;, sans-serif; font-weight: 500; line-height: 1.1; color: rgb(15, 38, 92); margin-top: 10px; margin-bottom: 10px; font-size: 20px; padding-top: 11px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Autorización para el Reporte y Consulta de Información ante los Operadores de Bancos de Datos de Información Financiera y/o Crediticia (Ley 1266 de 2008)</h4>
    <p style="box-sizing: border-box; margin: 0px 0px 10px; line-height: 1.8em; padding-top: 11px; color: rgb(89, 89, 89); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 100; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        Con la finalidad de que el BANCO PICHINCHA pueda dar trámite a mi solicitud de nuevos productos, evaluar y estudiar mi comportamiento crediticio y comercial y mantener actualizada mi información financiera, crediticia y comercial ante los operadores de bancos de datos, AUTORIZO al BANCO PICHINCHA para que: i) obtenga toda la información y referencias relativas a mi persona, a mi comportamiento crediticio y comercial, mis hábitos de pago, el manejo de la(s) cuenta(s) corriente(s) y de ahorros, de tarjetas de crédito, de otros productos financieros y/o de servicios contratados con el sector financiero y/o con el sector real y, en general, el cumplimiento dado a mis obligaciones; ii) consulte ante los operadores de bancos de datos, así como ante cualquier otra entidad de características similares que en el futuro se establezca, mi endeudamiento con el sector financiero, así como la información comercial disponible sobre el cumplimiento dado a los compromisos adquiridos con dicho(s) 
        sector(es); iii) incluya mi nombre, apellidos y tipo y número de mi documento de identificación, y demás información que se haga necesaria, en los archivos de deudores y obligados que llevan los operadores de bancos de datos, o cualquiera otra entidad que en el futuro se establezca con ese propósito, reportando el comportamiento positivo o negativo que se presente en la atención de las obligaciones a mi cargo. La autorización de reporte aquí establecida se hace extensiva a cualquier persona natural o jurídica que en el futuro llegue a ostentar la calidad de acreedor en relación con la(s) obligación(es) contraída(s) con el BANCO PICHINCHA; iv) consulte y procese mi información ante los operadores de bancos de datos y operadores de información y riesgo (Cifin, Experian, Covinoc, Fenalcheque) o cualquier otra que en un futuro se establezca; v) entregue o comparta mi información con personas jurídicas que administran bases de datos, para efectos de prevención y control de fraudes y 
        selección de riesgos; vi) remita vía correo electrónico y/o físico, según lo estime pertinente, a la(s) dirección(direcciones) suministradas por mí en este Sitio Web y/o en los registros de esa Entidad Financiera la notificación previa de que trata el artículo 21 de la Ley 1266 de 2008 y/o cualquier otra norma que lo modifique o adicione; vii) conserve, con las debidas actualizaciones y durante el período necesario señalado en la Ley, mi información crediticia; viii) reporte a las autoridades públicas, tributarias, aduaneras o judiciales, la información que requieran en el desarrollo de sus funciones; ix) ejerza el derecho de inspección para corroborar en cualquier tiempo que la información que he suministrado para la aprobación del (de los) producto(s) y/o servicio(s) es veraz, completa, exacta y actualizada; y, x) para que en el evento de negarse la solicitud de vinculación al Banco y/o el otorgamiento de uno o varios de los productos y/o servicios que éste ofrece, dicha Entidad 
        destruya los documentos que se aportan como soporte de la respectiva solicitud, dejando al efecto constancia expresa de su destrucción. El resultado del análisis para acceder al producto, me será informado a través de alguno de los medios de contacto que he suministrado.</p>
    <h4 style="box-sizing: border-box; font-family: &quot;Open Sans&quot;, sans-serif; font-weight: 500; line-height: 1.1; color: rgb(15, 38, 92); margin-top: 10px; margin-bottom: 10px; font-size: 20px; padding-top: 11px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Autorización para el Tratamiento de la Información Personal (Ley 1581 de 2012)</h4>
    <p style="box-sizing: border-box; margin: 0px 0px 10px; line-height: 1.8em; padding-top: 11px; color: rgb(89, 89, 89); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 100; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        De manera libre, voluntaria y expresa autorizo al BANCO PICHINCHA para que lleve a cabo el tratamiento de mis datos personales. En virtud de dicha autorización de tratamiento, el BANCO PICHINCHA podrá recolectar, almacenar, usar, circular, transferir, trasmitir, suprimir y/o actualizar mis datos e información personal, la cual, es suministrada por mí a través del Sitio Web www.bancopichincha.com.co. Mis datos e información personal podrán ser sujetos de tratamiento por el BANCO PICHINCHA, sus Encargados o Personas Responsables a quienes él les haya transmitido o transferido la información. En ese sentido, el tratamiento por la presente autorización permitido al BANCO PICHINCHA y a quien tenga la calidad de Encargado o Persona Responsable podrá tener por objeto las finalidades legítimas de: i) cumplir las obligaciones contractuales y reglamentarias, así como para la prestación de los servicios contratados; ii) atender y dar solución a las solicitudes, peticiones, quejas o reclamos 
        formulados al Banco; iii) crear y actualizar los perfiles transaccionales; iv) realizar gestiones comerciales; v) ofrecer productos o servicios, propios o de terceros; vi) realizar labores para que se avalen, afiancen o garanticen las operaciones de crédito; vii) realizar labores para que se origine mi vinculación al Banco como Cliente de uno o varios productos y servicios financieros pudiendo compartir información con terceros, tales como, Compañías Aseguradoras, Intermediarios de Seguros, Instituciones Educativas, Concesionarios, y Entidades Públicas y/o Privadas de cualquier naturaleza con las que se tengan Convenios de Libranza y/u otro tipo de alianzas comerciales, entre otros; viii) realizar gestiones de cobranza; ix) informar sobre los cambios realizados a los productos y servicios del portafolio del Banco; x) informar sobre las campañas y estrategias promocionales y de mercadeo; xi) analizar las tendencias y comportamientos de consumo de los consumidores financieros; xii) 
        recibir información, ofertas comerciales y publicitarias de productos del Banco y de aliados de éste; xiii) recibir cualquier tipo de información y/o comunicación que el Banco estime necesario; y, xiv) se adelanten todos los procesos de relacionamiento con el cliente (soportados o no en tecnología), para un abordaje integral con todos mis productos y soluciones contratadas con el BANCO PICHINCHA, entre otros permitidos por la Ley. Conozco y entiendo que las respuestas a las preguntas sobre el tratamiento de datos sensibles son facultativas. Como Titular de la información tengo derecho a conocer, actualizar y rectificar mis datos personales, solicitar prueba de la autorización otorgada para el tratamiento de la información, informarme sobre el uso que se ha dado a los mismos, revocar la autorización, solicitar la supresión de mis datos cuando sea procedente y acceder en forma gratuita a los mismos. En virtud de la presente autorización el responsable del tratamiento de la información 
        es&nbsp;BANCO PICHINCHA S.A.</p>
    <p style="box-sizing: border-box; margin: 0px 0px 10px; line-height: 1.8em; padding-top: 11px; color: rgb(89, 89, 89); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 100; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        La presente autorización se hace extensiva a quien represente los intereses del BANCO PICHINCHA y a quien la Entidad ceda sus derechos, obligaciones o su posición contractual a cualquier título, en relación con los productos o servicios de los que soy titular.</p>
    <p style="box-sizing: border-box; margin: 0px 0px 10px; line-height: 1.8em; padding-top: 11px; color: rgb(89, 89, 89); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 100; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        Para ejercer los derechos sobre sus datos personales puede comunicarse a la línea de Atención en Bogotá: 650 1000 o a Nivel Nacional al: 01 8000 919918. Para conocer nuestra política de privacidad visite&nbsp;https://www.bancopichincha.com.co</p>
    <h4 style="box-sizing: border-box; font-family: &quot;Open Sans&quot;, sans-serif; font-weight: 500; line-height: 1.1; color: rgb(15, 38, 92); margin-top: 10px; margin-bottom: 10px; font-size: 20px; padding-top: 11px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Autorización para Compartir Datos Personales con Entidades Pertenecientes al Grupo Económico</h4>
    <p style="box-sizing: border-box; margin: 0px 0px 10px; line-height: 1.8em; padding-top: 11px; color: rgb(89, 89, 89); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 100; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        Autorizo expresa y voluntariamente al BANCO PICHINCHA y/o a cualquier otra Entidad que represente sus derechos, a compartir mi información personal, financiera, crediticia y comercial como Cliente del Banco con cualquiera otra persona o Entidad Vinculada al Grupo Económico al que pertenece y/o llegue a pertenecer el BANCO PICHINCHA o la Entidad que represente sus derechos; para realizar el mismo tratamiento y con las mismas finalidades que haya llegado a autorizar al BANCO PICHINCHA.</p>
    <p style="box-sizing: border-box; margin: 0px 0px 10px; line-height: 1.8em; padding-top: 11px; color: rgb(89, 89, 89); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 100; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <strong style="box-sizing: border-box; font-weight: bold; font-family: OpenSans-Extrabold;"><u style="box-sizing: border-box;">Declaro haber leído cuidadosamente el contenido de este documento y haberlo comprendido a cabalidad, razón por la cual entiendo su alcance e implicaciones y con la aceptación de los términos y condiciones contenidos en este Sitio Web de BANCO PICHINCHA acepto expresamente:</u><span>&nbsp;</span>i) la autorización para el reporte y consulta de mi información ante los operadores de bancos de datos de información financiera y/o crediticia (Ley 1266 de 2008); ii) el tratamiento de mis datos personales<span>&nbsp;</span><u style="box-sizing: border-box;">y demás información</u>; y, iii) el compartir mis datos personales con Entidades pertenecientes al Grupo Económico.</strong></p>
    <p style="box-sizing: border-box; margin: 0px 0px 10px; line-height: 1.8em; padding-top: 11px; color: rgb(89, 89, 89); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 100; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <strong style="box-sizing: border-box; font-weight: bold; font-family: OpenSans-Extrabold;">El presente documento tendrá validez desde su aceptación de los términos y condiciones marcando el check de aceptación electrónica del formulario de solicitud, durante la vigencia de la relación del Cliente con el BANCO PICHINCHA y/o de quien en el futuro represente sus derechos, u ostente los derechos y/u obligaciones a cargo de BANCO PICHINCHA, y en general por el término establecido en la Ley.</strong></p>

    <form id="form1" runat="server">
        <div align="center">

            <asp:Button ID="btnVolver" CssClass="button" runat="server" Text="Volver" OnClick="btnVolver_Click" />

        </div>
    </form>
</body>
</html>
